### ISSUE TITLE
Cannot remove last favorite

### ISSUE THREAD

**Issue by jseppi** [USStateDept/State-TalentMAP#704]
### Steps to reproduce

1. Log in
1. Ensure you have only a single Favorited position associated with your account
1. On the Favorites section of your Profile page, click the heart icon of the favorited position to attempt to remove the favorite.

The same bug happens from other places where you can remove the "favorited" status of a position, such as on the Position Details page.

### Expected behavior

The favorite status is removed from the position and the account has no remaining favorited positions.

### Actual behavior

The favorited position is not removed. An HTTP error is displayed in the browser console.

<img width="718" alt="screen shot 2017-10-03 at 12 40 07 pm" src="https://user-images.githubusercontent.com/697848/31139905-941a7fda-a838-11e7-8a36-7c322b334f7c.png">

<img width="224" alt="screen shot 2017-10-03 at 12 46 00 pm" src="https://user-images.githubusercontent.com/697848/31140018-da66fa36-a838-11e7-8d46-e3e939c038b0.png">

**Comment by mjoyce91** [comment]
I ran into this during development and forgot to call it out. This is due to the following error message:

`{"favorite_positions":["This list may not be empty."]}`

@afrasier - can we allow having an empty list?

**Comment by mjoyce91** [comment]
Yes, we'll be able to simplify it with the new `DELETE /api/v1/position/{id}/favorite/` and `PUT /api/v1/position/{id}/favorite/`. Before we had those routes, I had to pull the entire profile to ensure the favorites array was up to date, and then run a `PATCH /api/v1/profile/`. Excluding any `OPTIONS` requests, that brings it down to 2 requests (patching/deleting the ID, and then refreshing the entire list). I'll open an issue to update those requests.

**Comment by afrasier** [comment]
I'm pretty sure using the `{id}/favorite/` routes allows an empty list. Please correct me if I'm wrong.

**Comment by mjoyce91** [comment]
@afraiser - Just double checked, and the error only occurs when you attempt the `PATCH /api/v1/profile/` with an empty array, opposed to deleting the last, single favorite with `DELETE /api/v1/position/{id}/favorite/`. Since we're migrating to the latter endpoint, it shouldn't be an issue - but if may be worth looking into.

**Comment by mjoyce91** [comment]
@jseppi - another aspect to the many requests is that when I added the Profile Favorites sub-section, I needed to call `/api/v1/position/favorites/` in order to get the favorited positions with **all** their data points (opposed to the limited data the profile object offers) to refresh. For convenience, I applied that logic to the same function used across all favorites refreshing, when it's really only needed in that profile sub-section.
